export const chartPages = [
  {
    slug: 'reservas',
    variableId: 1,
    pageTitle: 'Reservas Internacionales del BCRA',
    chartTitle: 'Reservas del BCRA',
    label: 'Reservas',
    chartType: 'bar',
  },
  {
    slug: 'tipo-de-cambio-minorista',
    variableId: 4,
    pageTitle: 'Tipo de Cambio Minorista',
    chartTitle: 'Tipo de Cambio',
    label: 'Tipo de Cambio',
    chartType: 'line',
  },
  {
    slug: 'tasa-de-politica-monetaria',
    variableId: 6,
    pageTitle: 'Tasa de Política Monetaria',
    chartTitle: 'Tasa de Política Monetaria',
    label: 'Tasa',
    chartType: 'line',
  },
  {
    slug: 'tasa-de-interes-prestamos-personales',
    variableId: 14,
    pageTitle: 'Tasa de Interés Préstamos Personales',
    chartTitle: 'Tasa de Interés Préstamos Personales',
    label: 'Tasa',
    chartType: 'line',
  },
  {
    slug: 'dinero-en-circulacion',
    variableId: 16,
    pageTitle: 'Dinero en Circulación',
    chartTitle: 'Dinero en Circulación',
    label: 'Dinero',
    chartType: 'bar',
  },
  {
    slug: 'billetes-y-monedas-en-poder-del-publico',
    variableId: 17,
    pageTitle: 'Billetes y Monedas en Poder del Público',
    chartTitle: 'Billetes y Monedas en Poder del Público',
    label: 'Dinero',
    chartType: 'bar',
  },
  // Agrega más configuraciones aquí
];